# Generated by Django 5.0.7 on 2025-01-20 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del tatuador')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('profile_image', models.URLField(blank=True, verbose_name='Imagen de perfil')),
                ('contact_info', models.TextField(blank=True, verbose_name='Información de contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Etiqueta')),
            ],
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='categoria',
        ),
        migrations.CreateModel(
            name='Tattoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título del tatuaje')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image_url', models.URLField(verbose_name='URL de la imagen')),
                ('style', models.CharField(blank=True, max_length=50, verbose_name='Estilo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tattoos', to='core.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Puntuación')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
                ('tattoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.tattoo')),
            ],
            options={
                'unique_together': {('user', 'tattoo')},
            },
        ),
        migrations.CreateModel(
            name='TattooTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tattoo_tags', to='core.tag')),
                ('tattoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tattoo_tags', to='core.tattoo')),
            ],
            options={
                'unique_together': {('tattoo', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorited_by', to='core.tattoo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
