# Generated by Django 5.1.5 on 2025-01-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_persona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
