# Generated by Django 5.1.5 on 2025-01-31 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_carrito_cita'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cita',
        ),
    ]
