# Generated by Django 5.1.5 on 2025-01-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='tattoo',
            name='precio',
            field=models.FloatField(default=0, verbose_name='Precio'),
            preserve_default=False,
        ),
    ]
